### ISSUE TITLE
判断两个控件相交的时候有个判断条件写错了？

### ISSUE THREAD

**Issue by Vistoryseed** [FireMou/DVPieChart#1]
rect1.origin.y < CGRectGetMaxY(rect) && rect1.origin.y < CGRectGetMaxY(rect)这里应该是说rect1的上方和rect的下方相重叠的

**Comment by FireMou** [comment]
嗯，多谢提醒，我注意到了前后的判断条件是一样的，这是不对的，稍后会更新代码，再次感谢！
