### ISSUE TITLE
数据的最后一条计算有问题

### ISSUE THREAD

**Issue by afunnyrainman** [FireMou/DVPieChart#2]
![d633a8c0-db4b-4fa2-b23f-1bc15d648e1a](https://user-images.githubusercontent.com/22904462/51360786-18b95c00-1b08-11e9-89ee-f6ceadf082ca.png)

**Comment by afunnyrainman** [comment]
最后一条数据的文字描述跑没了。

**Comment by afunnyrainman** [comment]
最上面的一条数据跑没了。

**Comment by afunnyrainman** [comment]
![e74c345e-7976-4181-a357-328f2f529e0a](https://user-images.githubusercontent.com/22904462/51361091-58cd0e80-1b09-11e9-865a-a96d627b89c6.png)

**Comment by afunnyrainman** [comment]
大佬,真是不好意思。。。

**Comment by FireMou** [comment]
这个饼图的计算还是存在一些问题的。第一、数据源不要过多，第二、尽量让起始点在水平中间的位置，不要在垂直中间的位置。有时间的话，我会对其进行修改。另有一备选方案，当时我们想让饼图可以随手势旋转，如着急，可以找找能旋转的饼图，这样哪怕重叠，也可在旋转过程中让其完全显示。
